### ISSUE TITLE
Product Description

### ISSUE THREAD

**Issue by s-xync** [s-xync/auction-away#1]
# Product Description
Have to come up with a very good product description on auction away
These question have to be answered by the product description

- What is your product? Who is the target audience you expect to use the product? What problem does it solve?  
- What alternatives exist, and what are their strengths and weaknesses? How will your system be different, from the user's point of view?  
- What are its major features?  
- What are its non-functional requirements?  
- What is product environment and dependency?  
- What external documentation will you provide that will enable users to understand and use your product?

**Comment by ahmedshoaib** [comment]
Done
