### ISSUE TITLE
Product Backlog

### ISSUE THREAD

**Issue by s-xync** [s-xync/auction-away#4]
# product Backlog  
Have to put together an ordered list of requirements that for the project. It should contain of features, requirements, etc. whatever must be done to successfully deliver the project. We should prioritise those product backlog items (PBIs) based on considerations such as risk, business value, dependencies, size, and date needed.

Items can be added in story format. The product backlog is what will be delivered, ordered into the sequence in which it should be delivered.

**Comment by ahmedshoaib** [comment]
added to :  https://github.com/s-xync/auction-away/projects/1#column-2068307
as well as in the docs folder
